<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activity' => '',
    'Add' => '',
    'Assigned To' => '',
    'Author' => '',
    'Author ID' => '',
    'Branch Count' => '',
    'Branches' => '',
    'Change' => '',
    'Changeset ID' => '',
    'Closed' => '',
    'Comment ID' => '',
    'Commit Date' => '',
    'Content' => '',
    'Create User ID' => '',
    'Created' => '',
    'Del' => '',
    'Description' => '',
    'Done Ratio' => '',
    'Edit' => '',
    'Effective Date' => '',
    'Help' => 'Hjælp',
    'Homepage' => '',
    'ID' => '',
    'Identifier' => '',
    'Is In Chlog' => '',
    'Is In Roadmap' => '',
    'Issue Category ID' => '',
    'Issue From' => '',
    'Issue ID' => '',
    'Issue Priority ID' => '',
    'Issue To' => '',
    'Issues' => '',
    'Last Comment' => '',
    'Local Path' => '',
    'Message' => '',
    'Modified' => '',
    'Name' => '',
    'Navigation' => '',
    'Overview' => '',
    'Parent Count' => '',
    'Parents' => '',
    'Position' => '',
    'Pre Done Ratio' => '',
    'Project ID' => '',
    'Public' => '',
    'Relation Type ID' => '',
    'Revision' => '',
    'Roadmap' => '',
    'Role' => '',
    'Scm ID' => '',
    'Short Rev' => '',
    'Size' => '',
    'Status' => '',
    'Subject' => '',
    'Tag Count' => '',
    'Tags' => '',
    'The Date' => '',
    'Title' => '',
    'Tracker ID' => '',
    'Type' => '',
    'Unique Ident' => '',
    'Update User ID' => '',
    'Updated By' => '',
    'Url' => '',
    'User ID' => '',
    'Version ID' => '',
    'Version Order' => '',
    'Dashboard' => 'Betjeningspanel',
    'Projects' => 'Projekter',
];
