<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assigned To' => '',
    'Author ID' => '',
    'Branch Count' => '',
    'Branches' => '',
    'Change' => '',
    'Changeset ID' => '',
    'Comment ID' => '',
    'Commit Date' => '',
    'Create User ID' => '',
    'Dashboard' => 'Betjeningspanel',
    'Del' => '',
    'Done Ratio' => '',
    'Edit' => '',
    'Effective Date' => '',
    'Help' => 'Hjælp',
    'ID' => '',
    'Identifier' => '',
    'Is In Chlog' => '',
    'Is In Roadmap' => '',
    'Issue Category ID' => '',
    'Issue From' => '',
    'Issue ID' => '',
    'Issue Priority ID' => '',
    'Issue To' => '',
    'Issues' => 'Sager',
    'Local Path' => '',
    'Navigation' => '',
    'Parent Count' => '',
    'Parents' => '',
    'Position' => '',
    'Pre Done Ratio' => '',
    'Project ID' => '',
    'Projects' => 'Projekter',
    'Public' => 'Offentlig',
    'Relation Type ID' => '',
    'Revision' => '',
    'Role' => 'Rolle',
    'Scm ID' => '',
    'Short Rev' => '',
    'Size' => 'Størrelse',
    'Status' => '',
    'Subject' => 'Emne',
    'Tag Count' => '',
    'Tags' => '',
    'The Date' => '',
    'Title' => 'Tittel',
    'Tracker ID' => '',
    'Type' => '',
    'Unique Ident' => '',
    'Update User ID' => '',
    'Updated By' => 'Opdateret Af',
    'Url' => '',
    'User ID' => '',
    'Version ID' => '',
    'Version Order' => '',
    'Activity' => 'Aktivitet',
    'Add' => 'Tilføj',
    'Author' => 'Forfatter',
    'Closed' => 'Lukket',
    'Content' => 'Indhold',
    'Created' => 'Oprettet',
    'Description' => 'Beskrivelse',
    'Homepage' => 'Hjemmeside',
    'Last Comment' => 'Seneste Kommentar',
    'Message' => 'Besked',
    'Modified' => 'Ændret',
    'Name' => 'Navn',
    'Overview' => 'Overblik',
    'Roadmap' => 'Køreplan',
];
