<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Assignments have been updated' => 'Tildelinger opdateret',
    'Auth item with such name already exists' => '',
    'Children' => 'Under-elementer',
    'Class "{0}" does not exist' => '',
    'Classname of the rule associated with this item' => '',
    'Create' => 'Tilføj',
    'Create new permission' => 'Tilføj ny tilladelse',
    'Create new role' => 'Tilføj ny rolle',
    'Description' => 'Beskrivelse',
    'Invalid value' => 'Ugyldig værdi',
    'Item has been created' => 'Element tilføjet',
    'Item has been updated' => 'Element opdateret',
    'Items' => 'Elementer',
    'Name' => 'Navn',
    'New permission' => 'Ny tilladelse',
    'New role' => 'Ny rolle',
    'New user' => 'Ny bruger',
    'Permissions' => 'Tilladelser',
    'Roles' => 'Roller',
    'Rule' => 'Regel',
    'Rule class can not be instantiated' => '',
    'Rule class must extend "yii\rbac\Rule"' => '',
    'Rule name' => 'Rollenavn',
    'Save' => 'Gem',
    'The item description (Optional).' => 'Element beskrivelse (ikke påkrævet)',
    'The name of the item.' => 'Elementets navn.',
    'There is neither role nor permission with name "{0}"' => 'Der findes hverken rolle eller tilladelse ved navn "{0}"',
    'Update assignments' => 'Opdater tildelinger',
    'Update permission' => 'Opdater tilladelser',
    'Update role' => 'Opdater rolle',
    'Users' => 'Brugere',
];
