# Your project's server will run on localhost:xxxx at this port
PROXY: "https://bugitor.dev"
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "assets/dist"
  # Paths to fonts
  fonts:
    - "vendor/bower/font-awesome/fonts/**/*"
    - "vendor/bower/bootstrap/fonts/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "vendor/bower/bootstrap-sass/assets/stylesheets"
    - "vendor/bower/font-awesome/scss"
    - "vendor/bower/sass-rem"
  # Paths to JavaScript libraries, which are compined into one file
  javascript:
    - "vendor/bower/jquery/dist/jquery.js"
    - "vendor/bower/bootstrap-sass/assets/javascripts/bootstrap.js"
    - "vendor/yiisoft/yii2/assets/yii.js"
    - "vendor/yiisoft/yii2/assets/yii.validation.js"
    - "vendor/yiisoft/yii2/assets/yii.activeForm.js"
    # Paths to your own project code are here
    - "js/!(custom).js"
    - "js/custom.js"
