<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Congratulations!' => '',
  'Install Rights' => '',
  'Installation failed.' => '',
  'No' => '',
  'Notice: All your existing data will be lost.' => '',
  'Please confirm if you wish to reinstall.' => '',
  'Rights has been installed succesfully.' => '',
  'Rights is already installed!' => '',
  'Yes' => '',
  'You can start by generating your authorization items' => '',
  'You must be logged in to install Rights.' => '',
  'here' => '',
);
