<?php
return array(
    // REST patterns
    array('api/list', 'pattern' => 'api/<model:\w+>', 'verb' => 'GET'),
    array('api/view', 'pattern' => 'api/<model:\w+>/<id:\d+>', 'verb' => 'GET'),
    array('api/update', 'pattern' => 'api/<model:\w+>/<id:\d+>', 'verb' => 'PUT'),
    array('api/execute', 'pattern' => 'api/execute', 'verb' => 'POST'),
    array('api/delete', 'pattern' => 'api/<model:\w+>/<id:\d+>', 'verb' => 'DELETE'),
    array('api/create', 'pattern' => 'api/<model:\w+>', 'verb' => 'POST'),
    '/projects/' => 'project/index',
    '/project/<_a:(create)>' => 'project/<_a>',
    '/projects/<identifier>' => 'project/view',
    '/projects/<identifier>/issues' => 'issue/index',
    '/projects/<identifier>/changesets' => 'changeset/index',
    '/projects/<identifier>/issue/<_a:(create)>' => 'issue/<_a>',
    '/projects/<identifier>/member/<_a:(create)>' => 'member/<_a>',
    '/projects/<identifier>/version/<_a:(create)>' => 'version/<_a>',
    '/projects/<identifier>/repository/<_a:(create)>' => 'repository/<_a>',
    '/projects/<identifier>/issueCategory/<_a:(create)>' => 'issueCategory/<_a>',
    '/projects/<identifier>/issue/<action:\w+>/<id:\d+>' => 'issue/<action>',
    '/projects/<identifier>/issues/<action:\w+>/<id:\d+>' => 'issue/<action>',
    '/projects/<identifier>/member/<action:\w+>/<id:\d+>' => 'member/<action>',
    '/projects/<identifier>/version/<action:\w+>/<id:\d+>' => 'version/<action>',
    '/projects/<identifier>/repository/<action:\w+>/<id:\d+>' => 'repository/<action>',
    '/projects/<identifier>/issueCategory/<action:\w+>/<id:\d+>' => 'issueCategory/<action>',
    '/projects/<identifier>/changeset/<action:\w+>/<id:\d+>' => 'changeset/<action>',
    '/projects/<identifier>/<_a:(activity|roadmap|code|settings)>' => 'project/<_a>',
    '<controller:\w+>/<id:\d+>' => '<controller>/view',
    '<controller:\w+>/<action:\w+>/<id:\d+>' => '<controller>/<action>',
    '<controller:\w+>/<action:\w+>' => '<controller>/<action>',
    'projects/<identifier>/feed' => array('project/feed', 'urlSuffix' => '.xml', 'caseSensitive' => false),
    '/issues/' => 'issue/index',
);
