<?php

Yii::import('bootstrap.widgets.TbMenu');

class BugitorMenu extends TbMenu
{

	/**
	 * Checks whether a menu item is active.
	 * This is done by checking if the currently requested URL is generated by the 'url' option
	 * of the menu item. Note that the GET parameters not specified in the 'url' option will be ignored.
	 * @param array $item the menu item to be checked
	 * @param string $route the route of the current request
	 * @return boolean whether the menu item is active
	 */
    protected function isItemActive($item, $route) {
        if (isset($item['id'])) {
            if($route === $item['id'])
                return true;
            if(($route === 'changeset/view')&&($item['id'] === 'project/code'))
                return true;
            if(($route === 'changeset/index')&&($item['id'] === 'project/code'))
                return true;
            if(($route === 'milestone/view')&&($item['id'] === 'project/roadmap'))
                return true;
            if(($route === 'issue/view')&&($item['id'] === 'issue/index'))
                return true;
            if(($route === 'issue/update')&&($item['id'] === 'issue/index'))
                return true;
            if(($route === 'project/admin')&&($item['id'] === 'project/admin'))
                return true;
            if(isset(Yii::app()->controller->module)){
                if((Yii::app()->controller->module->id === 'rights')&&($item['id'] === 'rights'))
                    return true;
            }
            if(isset(Yii::app()->controller->module)){
                if((Yii::app()->controller->module->id === 'user')&&($item['id'] === 'user'))
                    return true;
            }
            if((Yii::app()->controller->id === 'milestone')&&($item['id'] === 'project/settings')) {
                if(!($route === 'milestone/view'))
                    return true;
            }
            if((Yii::app()->controller->id === 'issueCategory')&&($item['id'] === 'project/settings')) {
                return true;
            }
            if((Yii::app()->controller->id === 'member')&&($item['id'] === 'project/settings')) {
                return true;
            }
            if((Yii::app()->controller->id === 'repository')&&($item['id'] === 'project/settings')) {
                return true;
            }
            if((Yii::app()->controller->id === 'projectLink')&&($item['id'] === 'project/settings')) {
                return true;
            }
            return false;
        }
        return false;
    }

}
